---
  - name: Start Locust Workers
    hosts: workers
    gather_facts: false
    remote_user: ec2-user
    tasks:

      - name: docker compose scale up
        shell: |
          cd load-test
          docker-compose scale locust-worker=15
        args:
          warn: false
  

